[package]
name = "i3ipc"
version = "0.8.1"
authors = ["Trevor Merrifield <trevorm42@gmail.com>"]
description = "A library for controlling i3-wm through its IPC interface"
license = "MIT"
repository = "https://github.com/tmerr/i3ipc-rs"

[dependencies]
byteorder = "1.1.0"
log = "0.3.8"
serde = "1.0.15"
serde_json = "1.0.3"

[features]
i3-4-12 = []
i3-4-13 = ["i3-4-12"]
i3-4-14 = ["i3-4-13"]
i3-next = ["i3-4-14"]
dox = ["i3-next"]

[package.metadata.docs.rs]
features = ["dox"]
